<?php

// the node ids of the period nodes
define(BEFORE, 489);
define(PERIOD1, 490);
define(PERIOD2, 492);
define(LUNCH, 494);
define(PERIOD3, 496);
define(PERIOD4, 498);
define(AFTER, 499);

// the role ids for certain roles
define(PAID, 8);
define(MEMBER, 7);

// the possible problems in signups
define(MISSING, 'MISSING');
define(DOUBLE, 'DOUBLE');
define(MISSING_PERSON, 'MISSING PERSON');

// the ids for certain jobs
define(COMMITTEE, 145);
define(TEACHER, 146);
define(TEACHING_ASSISTANT, 147);
define(ROOM_MONITOR, 148);
define(AUDITORIUM_MONITOR, 246);
define(GYM_MONITOR, 244);
define(GAME_MONITOR, 245);
define(PLAYGROUND_MONITOR, 1236);
define(COMPUTER, 5795);
define(UNASSIGNED, 6128);
define(LUNCH_TIME, 3866);
define(LUNCH_CLEAN, 2047);
define(CLEAN_UP, 251);
define(FLOATER, 247);
define(SET_UP, 242);
define(VOLUNTEER_MGR, 241);

// the ids for rooms
define(GYM, 174);
define(AUDITORIUM, 175);
define(LOBBY, 177);
define(MEETING, 178);
define(GAME, 179);
define(KITCHEN, 180);
define(DANCE, 181);
define(CERAMICS, 182);
define(CLASSROOM, 183);
define(ART1, 185);
define(ART2, 186);
define(OUTSIDE, 404);

?>